spring:
  profiles:
    active:
    - dev
---
server:
  port:8002
spring:
  application:
    name: GOGOU-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///gogou
    username: root
    password: 123456
  profiles: dev
  
eureka:
  client:
    service-url:
     defaultZone: http://www.eureka-7001.com:7001/eureka#告诉服务提供者要把服务注册到哪儿，注册中心的地址
feign:
   hystrix:
       enabled: true
