spring:
  profiles:
    active:
    - dev
---
server:
  port: 9101
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles: dev


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9101.com
    prefer-ip-address: true

zuul:
  routes:
    product.serviceId: gogou-product   #与服务提供者的名称一致,小写
    product.path: /product/**  #路由映射：/wbUser/**这个路径的访问都路由到serverId服务处理
  ignored-services: "*"  # 安全加固：忽略这个服务，如果要忽略所有的服务， “*”
  prefix: "/gogou"  # 统一前缀
